ministryofjustice/hmpps-launchpad-home-ui

server/utils/utils.test.ts, server/utils/utils.ts
**Ticket related to this PR:** 
https://trello.com/c/kWPVeSOS/75-launchpad-homepage-001-add-logo-and-formatted-todays-date-values
**Changes made in this PR:**
- comment removal
- addition of unit test to confirm date formatting 
**Screenshots:**
None required for this PR
=> Add unit test for formatDate()

server/errorHandler.test.ts, server/errorHandler.ts, server/views/pages/error.njk
**Ticket related to this PR:** 
https://dsdmoj.atlassian.net/browse/LNP-121
**Changes made in this PR:** 
- Update view
- Update error handler
- Update supporting unit tests
=> LNP-121 page not found

server/errorHandler.ts
=> Add missing '.'

server/routes/homepage/index.test.ts, server/services/linksService.ts
**Related to this ticket:**
https://dsdmoj.atlassian.net/browse/LNP-63
**Changes made:**
- Updated Self Service to Self-service as per updated designs
- Updated supporting unit test
=> Update self service title and supporting unit test

server/authentication/clientCredentials.ts, server/config.ts
Minor update to env variables no ticket required.
=> Update ENV variables

server/data/hmppsAuthClient.ts
no ticket needed. minor update.
=> Update token value

server/data/hmppsAuthClient.ts
=> Revert change

helm_deploy/values-dev.yaml
**Related to ticket:** 
https://dsdmoj.atlassian.net/browse/LNP-495
=> Add Cymulate allow list group

server/views/partials/homepage-layout.njk, server/views/partials/layout.njk
**Related to this ticket:**
https://dsdmoj.atlassian.net/browse/LNP-519
**Changes made in this PR:**
- Remove JQuery UI script tags from layout.njk
- Remove JQuery UI script tags from homepage-layout.njk
=> Remove JQuery UI links

server/config.ts, server/middleware/setUpWebSession.ts
Update lax to strict
Increase cookie duration to 1 day to enable security test
=> increase cookie timeout

server/views/pages/timetable.njk, server/views/partials/breadCrumb.njk
=> Fix indenting and apply breadcrumb change

server/routes/timetable/index.ts, server/views/pages/timetable.njk, server/views/partials/breadCrumb.njk
https://dsdmoj.atlassian.net/browse/LNP-646
=> LNP-646 Point profile link to content hub profile

helm_deploy/hmpps-launchpad-home-ui/values.yaml
The ticket is https://dsdmoj.atlassian.net/browse/LNP-702
=> LNP-702-Adding a firewall rule

server/views/pages/homepage.njk
https://dsdmoj.atlassian.net/browse/LNP-709
This is for test purpose only - Launching the profile box in the same tab to check if the issue still persists.
=> Do not launch a new tab when the profile box is clicked - For test purpose

server/data/hmppsAuthClient.test.ts, server/data/hmppsAuthClient.ts
[LNP-701](https://dsdmoj.atlassian.net/browse/LNP-701)
[LNP-701]: https://dsdmoj.atlassian.net/browse/LNP-701?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LNP-701- Removing the usage of username in code and assoicated tests

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-staging.yaml
[LNP-713](https://dsdmoj.atlassian.net/browse/LNP-713)
[LNP-713]: https://dsdmoj.atlassian.net/browse/LNP-713?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LNP-713-Shut-down-pods-lower-env-outside-office-hours

helm_deploy/values-dev.yaml
[LNP-733](https://dsdmoj.atlassian.net/browse/LNP-733)
[LNP-733]: https://dsdmoj.atlassian.net/browse/LNP-733?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LNP-733-Remove-bsi-from-allowlist-dev

server/views/partials/template.njk
[LNP-648](https://dsdmoj.atlassian.net/browse/LNP-648)
[LNP-648]: https://dsdmoj.atlassian.net/browse/LNP-648?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LNP-648-Adding-robots-meta-tag

server/config.ts
This PR contains
- Adding chelmsford config
https://dsdmoj.atlassian.net/browse/LNP-756
=> LNP-756-adding-chelmsford-config

server/app.ts, server/routes/testing/index.ts, server/utils/adjudications/formatAdjudication.ts, server/views/pages/testing/adjudications.njk
Test routes:
Profile - `/testing/ib48d19u/profile`
Adjudications - `/testing/ib48d19u/adjudications`
Single adjudication - `/testing/ib48d19u/adjudications/:chargeNumber`
Visits - `/testing/ib48d19u/visits`
https://dsdmoj.atlassian.net/browse/LNP-829
=> LNP-829: add test routes + views

server/views/partials/homepage-layout.njk, server/views/partials/layout.njk
[LNP-837](https://dsdmoj.atlassian.net/browse/LNP-837)
Fixing the paths to resolve the TypeError in the console tab.
[LNP-837]: https://dsdmoj.atlassian.net/browse/LNP-837?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LNP-837-fixing-paths-console-tab

server/config.ts
This PR contains
Adding Bullingdon config to LP
https://dsdmoj.atlassian.net/browse/LNP-757
=> LNP-757-adding-bullingdon-config

server/app.ts, server/constants/featureFlags.ts, server/constants/prisons.ts, server/routes/adjudications/index.test.ts, server/routes/adjudications/index.ts, server/routes/transactions/index.test.ts, server/routes/transactions/index.ts, server/routes/visits/index.test.ts, server/routes/visits/index.ts
- Adds setup for the /settings route
- Minor updates to add robustness/consistency
=> LNP-786: settings - routes/views

server/constants/featureFlags.ts, server/routes/homepage/index.test.ts, server/views/pages/homepage.njk, server/views/partials/layout.njk
- Update profile link to `/profile`
- Allow Erlestoke to access new profile features
- Update tests
- Fix js route
https://dsdmoj.atlassian.net/browse/LNP-863
=> LNP-855: change profile link

server/views/pages/adjudication.njk, server/views/pages/adjudications.njk
[LNP-1002](https://dsdmoj.atlassian.net/browse/LNP-1002)
- Fixing page title
[LNP-1002]: https://dsdmoj.atlassian.net/browse/LNP-1002?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LNP-1002-update-page-title

server/utils/adjudications/formatAdjudication.test.ts, server/utils/adjudications/formatAdjudication.ts, server/utils/adjudications/types.ts, server/utils/mocks/adjudications.ts, server/views/pages/adjudication.njk
- fix report date and time
- fix types/tests
=> fix report date and time

server/constants/featureFlags.ts, server/data/api/prisonApi/client.ts
Remove legacy adjudications endpoint.
=> LNP-997: remove legacy endpoint

server/views/partials/homepage-layout.njk, server/views/partials/layout.njk
Corrected the script path to resolve the _Uncaught TypeError_. 
Please refer to the ticket [LNP-1026](https://dsdmoj.atlassian.net/browse/LNP-1026) for more details.
[LNP-1026]: https://dsdmoj.atlassian.net/browse/LNP-1026?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LNP-1026-fix-file-path-error

server/views/partials/homepage-layout.njk, server/views/partials/layout.njk
Reverting the script path as it might break the transactions tab.
The original ticket is https://dsdmoj.atlassian.net/browse/LNP-1026
=> reverting-the-file-path

server/locales/cy.json, server/locales/en.json
This PR;
- adds `en.json` translations file
- adds `cy.json` translations file
Note: key names may need subtle refinement where required.
https://dsdmoj.atlassian.net/browse/LNP-1059
=> LNP-1059: add json translations

server/app.ts, server/middleware/setTranslationsEnabled.test.ts, server/middleware/setTranslationsEnabled.ts
https://dsdmoj.atlassian.net/browse/LNP-1081
=> LNP-1081: fix language persistence across routes

package-lock.json, server/@types/launchpad/index.d.ts, server/app.ts, server/constants/featureFlags.ts, server/data/api/prisonApi/client.ts, server/locales/cy.json, server/locales/en.json, server/middleware/setPrisonerContentHubUrl.ts, server/routes/homepage/index.test.ts, server/routes/homepage/index.ts, server/routes/timetable/index.ts, server/services/links/index.ts, server/services/prison/index.test.ts, server/services/prison/index.ts, server/utils/date/formatDateLocalized/index.ts, server/utils/mocks/events.ts, server/utils/mocks/links.ts, server/views/components/events-summary/index.njk, server/views/components/footer/macro.njk, server/views/components/footer/template.njk, server/views/components/link-tile/index.njk, server/views/components/tiles-panel/index.njk, server/views/pages/adjudication.njk, server/views/pages/adjudications.njk, server/views/pages/homepage.njk, server/views/pages/timetable.njk, server/views/pages/transactions.njk, server/views/pages/visits.njk, server/views/partials/template.njk, tsconfig.json
This PR;
- adds translations to the homepage
- updates all affected tests
- cleans up code
https://dsdmoj.atlassian.net/browse/LNP-1074
=> LNP-1074: add homepage translations + refine code

server/locales/cy.json, server/locales/en.json, server/routes/visits/index.ts, server/views/pages/visits.njk
https://dsdmoj.atlassian.net/browse/LNP-1078
=> LNP-1078: add social visitors translations

server/constants/featureFlags.ts, server/constants/prisons.ts
https://dsdmoj.atlassian.net/browse/LNP-1089
=> LNP-1089: add new prisons to config

server/constants/transactions.ts, server/locales/cy.json, server/locales/en.json, server/routes/transactions/index.ts, server/utils/transactions/createDamageObligationsTable.test.ts, server/utils/transactions/createDamageObligationsTable.ts, server/utils/transactions/createTransactionTable.test.ts, server/utils/transactions/createTransactionTable.ts, server/views/components/transactions/damage-obligations/table.njk, server/views/components/transactions/date-selection.njk, server/views/components/transactions/help.njk, server/views/components/transactions/table.njk, server/views/components/transactions/tabs.njk, server/views/pages/transactions.njk, server/views/pages/transactions/damage-obligations.njk
https://dsdmoj.atlassian.net/browse/LNP-1077
=> LNP-1077: add transactions translations

assets/scss/components/_header-bar.scss, server/constants/featureFlags.ts, server/locales/cy.json, server/locales/en.json, server/views/components/adjudications/hearing/macro.njk, server/views/components/adjudications/hearing/offences/macro.njk, server/views/components/adjudications/hearing/offences/punishments/macro.njk, server/views/components/adjudications/hearing/offences/punishments/template.njk, server/views/components/adjudications/hearing/offences/template.njk, server/views/components/adjudications/hearing/template.njk, server/views/pages/adjudication.njk, server/views/pages/adjudications.njk
https://dsdmoj.atlassian.net/browse/LNP-1076
=> LNP-1076: add adjudications translations

server/locales/cy.json, server/locales/en.json, server/routes/settings/index.ts, server/views/pages/remove-access.njk, server/views/pages/settings.njk
https://dsdmoj.atlassian.net/browse/LNP-1100
=> LNP-1100: settings translations

server/errorHandler.test.ts, server/views/pages/error.njk
https://dsdmoj.atlassian.net/browse/LNP-1101
=> LNP-1101: error page translations

server/routes/transactions/index.ts, server/utils/date/date.test.ts, server/utils/date/date.ts
https://dsdmoj.atlassian.net/browse/LNP-1106
=> LNP-1106: update date range translations

server/constants/featureFlags.ts
https://dsdmoj.atlassian.net/browse/LNP-1115
=> LNP-1115: turn on translations in Cardiff

server/utils/utils.test.ts, server/utils/utils.ts
Test was relying on actual config so could fail when config was changed.
=> Fix flakey test

helm_deploy/hmpps-launchpad-home-ui/values.yaml, package-lock.json, package.json, server/routes/homepage/index.test.ts, server/routes/homepage/index.ts
The logical first audit event to implement to test the full end to end auditing process.
Once this is working we can implement more events for other key actions.
=> LNP-1180: Add audit event when user visits the homepage

package-lock.json, package.json
https://github.com/advisories/GHSA-xffm-g5w8-qvg7
https://github.com/advisories/GHSA-fjxv-7rqg-78g4
=> update dependencies related to npm security alert

package-lock.json, package.json, server/routes/adjudications/index.test.ts, server/routes/adjudications/index.ts
Validating the `:chargeNumber` parameter in the URL
=> LNP-1258: Added validation to adjudication detail page URL
